server {
   listen 80;

    server_name wegia;

    location /api-wegia/ {
        proxy_pass ${BASE_URL_API_WEGIA}${BASE_URL_API_WEGIA_PATH};
        proxy_http_version 1.1;

        proxy_buffering off;
        proxy_cache_bypass 1;
    }

    location /api/upload/ {
        proxy_pass ${BASE_URL_API_WEGIA}/api/upload/;
        proxy_http_version 1.1;

        proxy_buffering off;
        proxy_cache_bypass 1;
    }

    location /api-pagar-me/ {
        proxy_pass ${BASE_URL_API_PAGAR_ME};
        proxy_http_version 1.1;

        proxy_buffering off;
        proxy_cache_bypass 1;
    }

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;

        proxy_buffering off;
        proxy_cache_bypass 1;
    }


}