<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissaoSeeder extends Seeder{

    public function run(): void
    {
        $permissoes = [
            ['nome'=>'Criar Pessoa','categoria'=>'Pessoa'],
            ['nome'=>'Visualizar Pessoa','categoria'=>'Pessoa'],
            ['nome'=>'Atualizar Pessoa','categoria'=>'Pessoa'],
            ['nome'=>'Deletar Pessoa','categoria'=>'Pessoa'],
            ['nome'=>'Criar Material e Patrimônio','categoria'=>'Material'],
            ['nome'=>'Visualizar Material e Patrimônio','categoria'=>'Material'],
            ['nome'=>'Atualizar Material e Patrimônio','categoria'=>'Material'],
            ['nome'=>'Deletar Material e Patrimônio','categoria'=>'Material'],
            ['nome'=>'Criar Memorando','categoria'=>'Memorando'],
            ['nome'=>'Visualizar Memorando','categoria'=>'Memorando'],
            ['nome'=>'Criar Despacho','categoria'=>'Memorando'],
            ['nome'=>'Visualizar Despacho','categoria'=>'Memorando'],
            ['nome'=>'Criar Sócio','categoria'=>'Socios'],
            ['nome'=>'Visualizar Sócio','categoria'=>'Socios'],
            ['nome'=>'Atualizar Sócio','categoria'=>'Socios'],
            ['nome'=>'Deletar Sócio','categoria'=>'Socios'],
            ['nome'=>'Criar Saúde','categoria'=>'Saude'],
            ['nome'=>'Visualizar Saúde','categoria'=>'Saude'],
            ['nome'=>'Atualizar Saúde','categoria'=>'Saude'],
            ['nome'=>'Deletar Saúde','categoria'=>'Saude'],
            ['nome'=>'Criar Pet','categoria'=>'Pet'],
            ['nome'=>'Visualizar Pet','categoria'=>'Pet'],
            ['nome'=>'Atualizar Pet','categoria'=>'Pet'],
            ['nome'=>'Deletar Pet','categoria'=>'Pet'],
            ['nome'=>'Visualizar Funcionário','categoria'=>'Pessoa'],
            ['nome'=>'Atualizar Funcionário','categoria'=>'Pessoa'],
            ['nome'=>'Deletar Funcionário','categoria'=>'Pessoa'],
            ['nome'=>'Criar Atendido','categoria'=>'Pessoa'],
            ['nome'=>'Visualizar Atendido','categoria'=>'Pessoa'],
            ['nome'=>'Atualizar Atendido','categoria'=>'Pessoa'],
            ['nome'=>'Deletar Atendido','categoria'=>'Pessoa'],
            ['nome'=>'Cadastrar Pet','categoria'=>'Pet'],
            ['nome'=>'Visualizar Saúde Pet','categoria'=>'Saude'],
            ['nome'=>'Atualizar Saúde Pet','categoria'=>'Saude'],
            ['nome'=>'Deletar Saúde Pet','categoria'=>'Saude'],
            ['nome'=>'Visualizar Informações Pet','categoria'=>'Pet'],
            ['nome'=>'Atualizar Informações Pet','categoria'=>'Pet'],
            ['nome'=>'Visualizar Adotantes Pet','categoria'=>'Pet'],
            ['nome'=>'Criar Raça','categoria'=>'Pet'],
            ['nome'=>'Visualizar Raça','categoria'=>'Pet'],
            ['nome'=>'Visualizar Especie','categoria'=>'Pet'],
            ['nome'=>'Criar Especie','categoria'=>'Pet'],
            ['nome'=>'Criar Ficha Medica','categoria'=>'Pet'],
            ['nome'=>'Atualizar Ficha Medica','categoria'=>'Pet'],
            ['nome'=>'Criar Medicamento','categoria'=>'Pet'],
            ['nome'=>'Atualizar Medicamento','categoria'=>'Pet'],
            ['nome'=>'Visualizar Medicamento','categoria'=>'Pet'],
            ['nome'=>'Criar Atendimento','categoria'=>'Pet'],
            ['nome'=>'Visualizar Atendimento','categoria'=>'Pet'],
            ['nome'=>'Criar Adoção','categoria'=>'Pet'],
            ['nome'=>'Atualizar Adoção','categoria'=>'Pet'],
            ['nome'=>'Atualizar senha de outras pessoas','categoria'=>'Pessoa'],
            ['nome'=>'Visualizar Dependente','categoria'=>'Pessoa'],
            ['nome'=>'Deletar Dependente','categoria'=>'Pessoa'],
            ['nome'=>'Criar Dependente','categoria'=>'Pessoa'],
            ['nome'=>'Criar Funcionario','categoria'=>'Pessoa'],
            ['nome'=>'Visualizar Funcionario','categoria'=>'Pessoa'],
            ['nome'=>'Atualizar Funcionario','categoria'=>'Pessoa'],
            ['nome'=>'Cadastrar Arquivo do Funcionario','categoria'=>'Pessoa'],
            ['nome'=>'Visualizar Arquivo do Funcionario','categoria'=>'Pessoa'],
            ['nome'=>'Deletar Arquivo do Funcionario','categoria'=>'Pessoa'],
            ['nome'=>'Visualizar Outras Informações do Funcionario','categoria'=>'Pessoa'],
            ['nome'=>'Criar Outras Informações do Funcionario','categoria'=>'Pessoa'],
            ['nome'=>'Deletar Outras Informações do Funcionario','categoria'=>'Pessoa'],
            ['nome'=>'Visualizar Funcionario Quadro Horario','categoria'=>'Pessoa'],
            ['nome'=>'Criar Funcionario Quadro Horario','categoria'=>'Pessoa'],
            ['nome'=>'Visualizar Remuneração do Funcionario','categoria'=>'Pessoa'],
            ['nome'=>'Criar Remuneração do Funcionario','categoria'=>'Pessoa'],
            ['nome'=>'Deletar Remuneração do Funcionario','categoria'=>'Pessoa'],
            ['nome'=>'Atualizar Cargo do Funcionario','categoria'=>'Pessoa'],
            ['nome'=>'Criar Perfil','categoria'=>'Pessoa'],
            ['nome'=>'Visualizar Perfil','categoria'=>'Pessoa'],
            ['nome'=>'Visualizar Permissao','categoria'=>'Configuração'],
            ['nome'=>'Vincular Perfil a uma Permissao','categoria'=>'Configuração'],
            ['nome'=>'Atualizar Perfil','categoria'=>'Pessoa'],
            ['nome'=>'Criar Atendido','categoria'=>'Pessoa'],
            ['nome'=>'Visualizar Atendido','categoria'=>'Pessoa'],
            ['nome'=>'Visualizar Ocorrencia dos atendidos','categoria'=>'Pessoa'],
            ['nome'=>'Criar Ocorrencia dos atendidos','categoria'=>'Pessoa'],
            ['nome'=>'Visualizar tipo de atendido','categoria'=>'Pessoa'],
            ['nome'=>'Visualizar status de atendido','categoria'=>'Pessoa'],
            ['nome'=>'Criar tipo de arquivo','categoria'=>'Pessoa'],
            ['nome'=>'Visualizar tipo de arquivo','categoria'=>'Pessoa'],
            ['nome'=>'Visualizar Arquivo Da Pessoa','categoria'=>'Pessoa'],
            ['nome'=>'Criar Arquivo para Pessoa','categoria'=>'Pessoa'],
            ['nome'=>'Deletar Arquivo da Pessoa','categoria'=>'Pessoa'],
            ['nome'=>'Atualizar Memorando','categoria'=>'Memorando'],
            ['nome'=>'Criar Saúde Sinais Vitais','categoria'=>'Saude'],
            ['nome'=>'Visualizar Saúde Sinais Vitais','categoria'=>'Saude'],
            ['nome'=>'Criar Saúde Medico','categoria'=>'Saude'],
            ['nome'=>'Visualizar Saúde Medico','categoria'=>'Saude'],
            ['nome'=>'Criar Saúde Medicamento Administração','categoria'=>'Saude'],
            ['nome'=>'Visualizar Saúde Medicamento Administração','categoria'=>'Saude'],
            ['nome'=>'Atualizar Saúde Medicação','categoria'=>'Saude'],
            ['nome'=>'Visualizar Saúde Medicação','categoria'=>'Saude'],
            ['nome'=>'Criar Saúde Intercorrencia','categoria'=>'Saude'],
            ['nome'=>'Visualizar Saúde Intercorrencia','categoria'=>'Saude'],
            ['nome'=>'Criar Saúde Ficha Médica','categoria'=>'Saude'],
            ['nome'=>'Visualizar Saúde Ficha Médica','categoria'=>'Saude'],
            ['nome'=>'Atualizar Saúde Ficha Médica','categoria'=>'Saude'],
            ['nome'=>'Criar Saúde Historico Prontuario','categoria'=>'Saude'],
            ['nome'=>'Criar Saúde Tipos de Exame','categoria'=>'Saude'],
            ['nome'=>'Visualizar Saúde Tipos de Exame','categoria'=>'Saude'],
            ['nome'=>'Criar Saúde Exame','categoria'=>'Saude'],
            ['nome'=>'Visualizar Saúde Exame','categoria'=>'Saude'],
            ['nome'=>'Deletar Saúde Exame','categoria'=>'Saude'],
            ['nome'=>'Criar Saúde Enfermidade','categoria'=>'Saude'],
            ['nome'=>'Visualizar Saúde Enfermidade','categoria'=>'Saude'],
            ['nome'=>'Atualizar Saúde Enfermidade','categoria'=>'Saude'],
            ['nome'=>'Criar Saúde CID','categoria'=>'Saude'],
            ['nome'=>'Visualizar Saúde CID','categoria'=>'Saude'],
            ['nome'=>'Criar Saúde Atendimento','categoria'=>'Saude'],
            ['nome'=>'Visualizar Saúde Atendimento','categoria'=>'Saude'],
            ['nome'=>'Cadastrar Saúde alergia na ficha medica','categoria'=>'Saude'],
            ['nome'=>'Visualizar Saúde alergia na ficha medica','categoria'=>'Saude'],
            ['nome'=>'Deletar Saúde Alergia na Ficha Médica','categoria'=>'Saude'],
            ['nome'=>'Criar entrada de material','categoria'=>'Material'],
            ['nome'=>'Criar origem e saida de material','categoria'=>'Material'],
            ['nome'=>'Criar almoxarifado do material','categoria'=>'Material'],
            ['nome'=>'Criar tipo de movimentação do material','categoria'=>'Material'],
            ['nome'=>'Criar produto material','categoria'=>'Material'],
            ['nome'=>'Criar categoria material','categoria'=>'Material'],
            ['nome'=>'Criar unidade material','categoria'=>'Material'],
            ['nome'=>'Atualizar produto após entrada de material','categoria'=>'Material'],
            ['nome'=>'Deletar produto após entrada de material','categoria'=>'Material'],
            ['nome'=>'Atualizar produto após entrada de material','categoria'=>'Material'],
            ['nome'=>'Deletar produto após entrada de material','categoria'=>'Material'],
            ['nome'=>'Visualizar Entrada de material','categoria'=>'Material'],
            ['nome'=>'Criar saida de material','categoria'=>'Material'],
            ['nome'=>'Visualizar saída de material','categoria'=>'Material'],
            ['nome'=>'Atualizar produto após saída de material','categoria'=>'Material'],
            ['nome'=>'Deletar produto após saída de material','categoria'=>'Material'],
            ['nome'=>'Visualizar produto material','categoria'=>'Material'],
            ['nome'=>'Atualizar produto material','categoria'=>'Material'],
            ['nome'=>'Visualizar unidade material','categoria'=>'Material'],
            ['nome'=>'Atualizar unidade material','categoria'=>'Material'],
            ['nome'=>'Visualizar categoria material','categoria'=>'Material'],
            ['nome'=>'Atualizar categoria material','categoria'=>'Material'],
            ['nome'=>'Visualizar tipo de movimentação do material','categoria'=>'Material'],
            ['nome'=>'Atualizar tipo de movimentação do material','categoria'=>'Material'],
            ['nome'=>'Visualizar origem e saida de material','categoria'=>'Material'],
            ['nome'=>'Atualizar origem e saida de material','categoria'=>'Material'],
            ['nome'=>'Visualizar almoxarifado do material','categoria'=>'Material'],
            ['nome'=>'Atualizar almoxarifado do material','categoria'=>'Material'],
            ['nome'=>'Visualizar relatorio material','categoria'=>'Material'],
            ['nome'=>'Criar Gateway de contribuição','categoria'=>'Contribuição'],
            ['nome'=>'Visualizar Gateway de contribuição','categoria'=>'Contribuição'],
            ['nome'=>'Atualizar Gateway de contribuição','categoria'=>'Contribuição'],
            ['nome'=>'Criar regras de pagamento de contribuição','categoria'=>'Contribuição'],
            ['nome'=>'Visualizar regras de pagamento de contribuição','categoria'=>'Contribuição'],
            ['nome'=>'Atualizar regras de pagamento de contribuição','categoria'=>'Contribuição'],
            ['nome'=>'Criar meio de pagamento de contribuição','categoria'=>'Contribuição'],
            ['nome'=>'Visualizar meio de pagamento de contribuição','categoria'=>'Contribuição'],
            ['nome'=>'Atualizar meio de pagamento de contribuição','categoria'=>'Contribuição'],
            ['nome'=>'Visualizar as contribuições','categoria'=>'Contribuição'],
            ['nome'=>'Visualizar os Socios','categoria'=>'Socios'],
            ['nome'=>'Visualizar os Socios Aniversariante','categoria'=>'Socios'],
            ['nome'=>'Visualizar os Socios Gráfico','categoria'=>'Socios'],
            ['nome'=>'Visualizar os Socios Relatorio','categoria'=>'Socios'],
            ['nome'=>'Atualizar o Socio','categoria'=>'Socios'],
            ['nome'=>'Criar tag de Socio','categoria'=>'Socios'],
            ['nome'=>'Visualizar tag de Socio','categoria'=>'Socios'],
            ['nome'=>'Atualizar tag de Socio','categoria'=>'Socios'],
            ['nome'=>'Sincronizar pagamentos','categoria'=>'Socios'],
            ['nome'=>'Atualizar textos do conteudo do sistema','categoria'=>'Configuração'],
            ['nome'=>'Atualizar endereco da instituição','categoria'=>'Configuração'],
            ['nome'=>'Cadastrar contato da instituição','categoria'=>'Configuração'],
            ['nome'=>'Atualizar contato da instituição','categoria'=>'Configuração'],
            ['nome'=>'Deletar contato da instituição','categoria'=>'Configuração'],
        ];

        foreach ($permissoes as $p) {
            DB::table('permissao')->updateOrInsert(
                ['nome' => $p['nome']],
                ['categoria' => $p['categoria']]
            );
        }
    }

}
