sonar.projectKey=projeto-laravel
sonar.projectName=Projeto Laravel
sonar.projectVersion=1.0

# Diretórios a analisar
sonar.sources=api

sonar.exclusions=**/Providers/**, **/vendor/**, **/routes/**, **/migrations/**, **/resources/**, **/node_modules/**,\
docker-conf/**, **/lang/**, **/bootstrap/**, **/config/*, **/storage/**, **/public/**, **/tests/**,\
**/vite**, **/public/index.php


sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.token=sqa_2d662d94d3c9bcad7d56094e71d246c336d2bc8e

sonar.issue.ignore.multicriteria=e1,e2,e3

sonar.issue.ignore.multicriteria.e1.ruleKey=php:S117
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.php

sonar.issue.ignore.multicriteria.e2.ruleKey=php:S101
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.php

sonar.issue.ignore.multicriteria.e3.ruleKey=php:S116
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.php

sonar.issue.ignore.multiple=ignore-duplicate-id-placeholder
sonar.issue.ignore.multiple.ignore-duplicate-id-placeholder.ruleKey=php:S1192
sonar.issue.ignore.multiple.ignore-duplicate-id-placeholder.messagePattern=\{id\}
sonar.issue.ignore.multiple.ignore-duplicate-id-placeholder.resourceKeyPattern=^routes/.*$

