apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wegia-back-ingress
  namespace: wegia
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: api.wegia.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wegia-back
            port:
              number: 80
