apiVersion: v1
kind: Secret
metadata:
  name: wegia-back-secret
  namespace: wegia
type: Opaque
stringData:
  APP_KEY: "${APP_KEY}"
  DB_PASSWORD: "${DB_PASSWORD}"
  PRIVATE_KEY_PAGAR_ME: "${PRIVATE_KEY_PAGAR_ME}"
  BASE_URL_API_PAGAR_ME: "${BASE_URL_API_PAGAR_ME}"
  ALLOWED_IPS_PAGAR_ME: "${ALLOWED_IPS_PAGAR_ME}"
  MAIL_PASSWORD: "${MAIL_PASSWORD}"
