FROM python:3.12-slim AS builder

WORKDIR /app

RUN pip install --no-cache-dir \
    mkdocs==1.6.1 \
    mkdocs-material==9.6.21 \
    mkdocs-material-extensions==1.3.1

COPY mkdocs.yml /app
COPY docs /app/docs

RUN mkdocs build

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/site /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]