sonar.projectKey=wegia-nuxt
sonar.projectName=Projeto Wegia Nuxt
sonar.projectVersion=1.1

sonar.sources=app

sonar.exclusions=**/node_modules/**, **/.nuxt/**, **/dist/**

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.token=sqa_ab37069f8ea1158854a33e08742a79af39766364

sonar.issue.ignore.multicriteria=e1,e2

sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S1121
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.vue

sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S7781
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.vue