-- MySQL Script generated by MySQL Workbench
-- Fri Jul 23 17:58:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wegia
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wegia` ;

-- -----------------------------------------------------
-- Schema wegia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wegia` DEFAULT CHARACTER SET utf8mb4 ;
USE `wegia` ;


-- -----------------------------------------------------
-- Table `wegia`.`material_almoxarifado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`material_almoxarifado` (
  `id_almoxarifado` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(240) NOT NULL,
  PRIMARY KEY (`id_almoxarifado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pessoa` (
  `id_pessoa` INT(11) NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(120) NULL,
  `senha` VARCHAR(70) NULL DEFAULT NULL,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `sobrenome` VARCHAR(100) NULL DEFAULT NULL,
  `sexo` CHAR(1) NULL DEFAULT NULL,
  `telefone` VARCHAR(25) NULL DEFAULT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `imagem` LONGTEXT NULL DEFAULT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `estado` VARCHAR(5) NULL DEFAULT NULL,
  `cidade` VARCHAR(40) NULL DEFAULT NULL,
  `bairro` VARCHAR(40) NULL DEFAULT NULL,
  `logradouro` VARCHAR(100) NULL DEFAULT NULL,
  `numero_endereco` VARCHAR(80) NULL DEFAULT NULL,
  `complemento` VARCHAR(50) NULL DEFAULT NULL,
  `ibge` VARCHAR(20) NULL DEFAULT NULL,
  `registro_geral` VARCHAR(120) NULL DEFAULT NULL,
  `orgao_emissor` VARCHAR(120) NULL DEFAULT NULL,
  `data_expedicao` DATE NULL DEFAULT NULL,
  `nome_mae` VARCHAR(100) NULL DEFAULT NULL,
  `nome_pai` VARCHAR(100) NULL DEFAULT NULL,
  `tipo_sanguineo` VARCHAR(5) NULL DEFAULT NULL,
  `nivel_acesso` TINYINT(4) NULL DEFAULT '0',
  `adm_configurado` TINYINT(4) NULL DEFAULT '0',
  UNIQUE INDEX (`cpf` ASC),
  PRIMARY KEY (`id_pessoa`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`pessoa_dependente`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `wegia`.`pessoa_dependente` (
  id_dependente INT AUTO_INCREMENT PRIMARY KEY,
  id_pessoa INT NOT NULL,
  id_dependente_pessoa INT NOT NULL,
  parentesco ENUM(
    'Companheiro(a)',
    'Cônjuge',
    'Enteado(a)',
    'Ex-cônjuge',
    'Filho(a)',
    'Irmão(ã)',
    'Neto(a)',
    'Pais',
    'Outra relação de dependência'
  ) NOT NULL,
  CONSTRAINT fk_dependente_pessoa
    FOREIGN KEY (id_pessoa) REFERENCES pessoa(id_pessoa),
  CONSTRAINT fk_dependente_pessoa_dependente
    FOREIGN KEY (id_dependente_pessoa) REFERENCES pessoa(id_pessoa)
);

-- -----------------------------------------------------
-- Table `wegia`.`pessoa_tipo_arquivo`
-- -----------------------------------------------------

CREATE TABLE pessoa_tipo_arquivo (
    id_pessoa_tipo_arquivo INT AUTO_INCREMENT PRIMARY KEY,
    descricao VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `wegia`.`pessoa_arquivo`
-- -----------------------------------------------------

CREATE TABLE pessoa_arquivo (
    id_pessoa_arquivo INT AUTO_INCREMENT PRIMARY KEY,
    id_pessoa INT NOT NULL,
    id_pessoa_tipo_arquivo INT NOT NULL,
    data DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    extensao_arquivo VARCHAR(10) NOT NULL,
    nome_arquivo VARCHAR(255) NOT NULL,
    arquivo LONGBLOB NOT NULL,
    CONSTRAINT fk_pessoa_arquivo_pessoa FOREIGN KEY (id_pessoa)
        REFERENCES pessoa (id_pessoa)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_pessoa_arquivo_tipo FOREIGN KEY (id_pessoa_tipo_arquivo)
        REFERENCES pessoa_tipo_arquivo (id_pessoa_tipo_arquivo)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `wegia`.`permissao`
-- -----------------------------------------------------

CREATE TABLE permissao (
    id_permissao INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    categoria ENUM(
        'Pessoa',
        'Pet',
        'Material',
        'Memorando',
        'Socios',
        'Saude',
        'Contribuição',
        'Configuração'
    ) NOT NULL
);

-- -----------------------------------------------------
-- Table `wegia`.`perfil`
-- -----------------------------------------------------
CREATE TABLE perfil (
    id_perfil INT AUTO_INCREMENT PRIMARY KEY,
    cargo VARCHAR(100) NOT NULL,
    nome VARCHAR(100) NOT NULL
);

-- -----------------------------------------------------
-- Table `wegia`.`perfil_permissao`
-- -----------------------------------------------------
CREATE TABLE perfil_permissao (
    id_perfil INT NOT NULL,
    id_permissao INT NOT NULL,
    PRIMARY KEY (id_perfil, id_permissao),
    CONSTRAINT fk_perfil FOREIGN KEY (id_perfil) REFERENCES perfil(id_perfil) ON DELETE CASCADE,
    CONSTRAINT fk_permissao FOREIGN KEY (id_permissao) REFERENCES permissao(id_permissao) ON DELETE CASCADE
);

-- -----------------------------------------------------
-- Table `wegia`.`situacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`situacao` (
  `id_situacao` INT(11) NOT NULL AUTO_INCREMENT,
  `situacoes` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id_situacao`),
  UNIQUE INDEX `situacoes` (`situacoes` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`funcionario` (
    `id_funcionario` INT(11) NOT NULL AUTO_INCREMENT,
    `id_pessoa` INT(11) NOT NULL,
    `id_perfil` INT(11) NOT NULL,
    `id_situacao` INT(11) NOT NULL,
    `data_admissao` DATE NOT NULL,
    `pis` VARCHAR(140) NULL DEFAULT NULL,
    `ctps` VARCHAR(150) NOT NULL,
    `uf_ctps` VARCHAR(20) NULL DEFAULT NULL,
    `numero_titulo` VARCHAR(150) NULL DEFAULT NULL,
    `zona` VARCHAR(30) NULL DEFAULT NULL,
    `secao` VARCHAR(40) NULL DEFAULT NULL,
    `certificado_reservista_numero` VARCHAR(100) NULL DEFAULT NULL,
    `certificado_reservista_serie` VARCHAR(100) NULL DEFAULT NULL,
    PRIMARY KEY (`id_funcionario`),
    INDEX `id_pessoa` (`id_pessoa` ASC),
    INDEX `fk_funcionario_perfil1_idx` (`id_perfil` ASC),
    INDEX `fk_funcionario_situacao1_idx` (`id_situacao` ASC),
    CONSTRAINT `funcionario_ibfk_1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `wegia`.`pessoa` (`id_pessoa`),
    CONSTRAINT `fk_funcionario_perfil1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `wegia`.`perfil` (`id_perfil`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_funcionario_situacao1`
    FOREIGN KEY (`id_situacao`)
    REFERENCES `wegia`.`situacao` (`id_situacao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`almoxarife`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`almoxarife` (
  `id_almoxarife` INT(11) NOT NULL AUTO_INCREMENT,
  `id_funcionario` INT(11) NOT NULL,
  `id_almoxarifado` INT NOT NULL,
  `data_registro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_almoxarife`),
  INDEX `id_almoxarife` (`id_almoxarife` ASC),
  INDEX `almoxarife_ibfk_1` (`id_funcionario` ASC),
  INDEX `almoxarife_ibfk_2` (`id_almoxarifado` ASC),
  CONSTRAINT `almoxarife_ibfk_1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `wegia`.`funcionario` (`id_funcionario`),
  CONSTRAINT `almoxarife_ibfk_2`
    FOREIGN KEY (`id_almoxarifado`)
    REFERENCES `wegia`.`almoxarifado` (`id_almoxarifado`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`memorando`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`memorando` (
    `id_memorando` INT(11) NOT NULL AUTO_INCREMENT,
    `id_pessoa` INT(11) NOT NULL,
    `status_memorando` ENUM('Ativo', 'Lido', 'Não Lido', 'Importante', 'Pendente', 'Arquivado') NOT NULL DEFAULT 'Pendente',
    `titulo` TEXT NULL DEFAULT NULL,
    `data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id_memorando`),
    INDEX `id_pessoa` (`id_pessoa` ASC),
    CONSTRAINT `memorando_ibfk_1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `wegia`.`pessoa` (`id_pessoa`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`despacho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`despacho` (
  `id_despacho` INT(11) NOT NULL AUTO_INCREMENT,
  `id_memorando` INT(11) NOT NULL,
  `id_remetente` INT(11) NOT NULL,
  `id_destinatario` INT(11) NOT NULL,
  `texto` LONGTEXT NULL DEFAULT NULL,
  `data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_despacho`),
  INDEX `id_memorando` (`id_memorando` ASC),
  INDEX `id_remetente` (`id_remetente` ASC),
  INDEX `id_destinatario` (`id_destinatario` ASC),
  CONSTRAINT `despacho_ibfk_1`
    FOREIGN KEY (`id_memorando`)
    REFERENCES `wegia`.`memorando` (`id_memorando`),
  CONSTRAINT `despacho_ibfk_2`
    FOREIGN KEY (`id_remetente`)
    REFERENCES `wegia`.`pessoa` (`id_pessoa`),
  CONSTRAINT `despacho_ibfk_3`
    FOREIGN KEY (`id_destinatario`)
    REFERENCES `wegia`.`pessoa` (`id_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`anexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`anexo` (
  `id_anexo` INT(11) NOT NULL AUTO_INCREMENT,
  `id_despacho` INT(11) NOT NULL,
  `anexo` VARCHAR(100) NOT NULL,
  `extensao` VARCHAR(256) NOT NULL,
  `nome` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id_anexo`),
  INDEX `id_despacho` (`id_despacho` ASC),
  CONSTRAINT `anexo_ibfk_1`
    FOREIGN KEY (`id_despacho`)
    REFERENCES `wegia`.`despacho` (`id_despacho`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- View para consultar o utlimo despacho por memorando
-- -----------------------------------------------------

CREATE OR REPLACE VIEW view_ultimo_despacho_por_memorando AS
SELECT d.*, m.titulo, m.status_memorando, m.id_pessoa as criado_por, p.nome as origem
FROM despacho d
         JOIN (
    SELECT id_memorando, MAX(data) AS max_data
    FROM despacho
    GROUP BY id_memorando
) latest ON d.id_memorando = latest.id_memorando AND d.data = latest.max_data
         JOIN memorando m ON m.id_memorando = d.id_memorando
         JOIN pessoa p ON p.id_pessoa = d.id_remetente;

-- -----------------------------------------------------
-- Table `wegia`.`campo_imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`campo_imagem` (
  `id_campo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_campo` VARCHAR(40) NOT NULL,
  `tipo` ENUM('img', 'car') NOT NULL,
  PRIMARY KEY (`id_campo`),
  UNIQUE INDEX `nome_campo` (`nome_campo` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`material_parceiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`material_parceiro` (
    id_parceiro INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(14),
    cnpj VARCHAR(18),
    telefone VARCHAR(20)
)ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`material_tipo_movimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`material_tipo_movimentacao` (
    id_tipo_movimentacao INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    tipo ENUM('e', 's') NOT NULL
)ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`material_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`material_categoria` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `descricao` (`descricao` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`material_unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`material_unidade` (
  `id_unidade` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_unidade`),
  UNIQUE INDEX `descricao` (`descricao` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`material_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`material_produto` (
    `id_produto` INT(11) NOT NULL AUTO_INCREMENT,
    `id_categoria` INT(11) NOT NULL,
    `id_unidade` INT(11) NOT NULL,
    `descricao` VARCHAR(150) NOT NULL,
    `codigo` VARCHAR(15) NULL DEFAULT NULL,
    `oculto` TINYINT NULL DEFAULT false,
    PRIMARY KEY (`id_produto`),
    UNIQUE INDEX `descricao` (`descricao` ASC),
    UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
    INDEX `id_categoria` (`id_categoria` ASC),
    INDEX `id_unidade` (`id_unidade` ASC),
    CONSTRAINT `material_produto_ibfk_1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `wegia`.`material_categoria` (`id_categoria`),
    CONSTRAINT `material_produto_ibfk_2`
    FOREIGN KEY (`id_unidade`)
    REFERENCES `wegia`.`material_unidade` (`id_unidade`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`material_transacao`
-- -----------------------------------------------------
CREATE TABLE material_transacao (
    id_transacao INT AUTO_INCREMENT PRIMARY KEY,
    id_tipo_movimentacao INT NOT NULL,
    id_almoxarifado INT NOT NULL,
    id_responsavel INT NOT NULL,
    id_parceiro INT NOT NULL,
    data DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (id_tipo_movimentacao) REFERENCES material_tipo_movimentacao(id_tipo_movimentacao),
    FOREIGN KEY (id_almoxarifado) REFERENCES material_almoxarifado(id_almoxarifado),
    FOREIGN KEY (id_parceiro) REFERENCES material_parceiro(id_parceiro),
    FOREIGN KEY (id_responsavel) REFERENCES pessoa(id_pessoa)
);

-- -----------------------------------------------------
-- Table `wegia`.`material_transacao_produto`
-- -----------------------------------------------------
CREATE TABLE material_transacao_produto (
    id_transacao_produto INT AUTO_INCREMENT PRIMARY KEY,
    id_transacao INT NOT NULL,
    id_produto INT NOT NULL,
    quantidade INT NOT NULL,
    valor_unitario DECIMAL(10,2) NOT NULL,

    FOREIGN KEY (id_transacao) REFERENCES material_transacao(id_transacao) ON DELETE CASCADE,
    FOREIGN KEY (id_produto) REFERENCES material_produto(id_produto)
);

-- -----------------------------------------------------
-- Table `wegia`.`material_transacao_produto_logs`
-- -----------------------------------------------------
CREATE TABLE material_transacao_produto_logs (
    id_transacao_produto_log INT AUTO_INCREMENT PRIMARY KEY,
    id_transacao_produto INT NOT NULL,
    id_transacao INT NOT NULL,
    id_produto INT NOT NULL,
    quantidade INT NOT NULL,
    valor_unitario DECIMAL(10,2) NOT NULL,
    id_usuario_acao INT NOT NULL,
    acao ENUM('create', 'update', 'delete') NOT NULL,
    data_acao DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------
-- View `wegia`.`view_material_relatorio`
-- -----------------------------------------------------
CREATE OR REPLACE VIEW view_material_relatorio AS
SELECT
    t.id_transacao,
    tm.id_tipo_movimentacao,
    t.id_responsavel,
    a.id_almoxarifado,
    p.id_produto,
    t.id_parceiro,
    t.data,
    tm.nome AS tipo_movimentacao,
    tm.tipo AS tipo,
    a.descricao AS almoxarifado,
    pa.nome AS parceiro,
    r.nome AS responsavel,
    p.descricao AS produto,
    u.descricao AS unidade,
    tp.quantidade,
    tp.valor_unitario,
    (tp.quantidade * tp.valor_unitario) AS total
FROM material_transacao t
         JOIN material_transacao_produto tp ON tp.id_transacao = t.id_transacao
         JOIN material_produto p ON p.id_produto = tp.id_produto
         JOIN material_unidade u ON u.id_unidade = p.id_unidade
         JOIN material_almoxarifado a ON a.id_almoxarifado = t.id_almoxarifado
         JOIN material_parceiro pa ON pa.id_parceiro = t.id_parceiro
         JOIN pessoa r ON r.id_pessoa = t.id_responsavel
         JOIN material_tipo_movimentacao tm ON tm.id_tipo_movimentacao = t.id_tipo_movimentacao;

-- -----------------------------------------------------
-- View `wegia`.`view_estoque_atual`
-- -----------------------------------------------------
CREATE OR REPLACE VIEW view_estoque_atual AS
SELECT
    tp.id_produto,
    mp.descricao AS nome_produto,
    t.id_almoxarifado,
    SUM(
            CASE
                WHEN tm.tipo = 'e' THEN tp.quantidade
                WHEN tm.tipo = 's' THEN -tp.quantidade
                ELSE 0
                END
    ) AS estoque
FROM material_transacao_produto tp
         JOIN material_transacao t ON tp.id_transacao = t.id_transacao
         JOIN material_tipo_movimentacao tm ON t.id_tipo_movimentacao = tm.id_tipo_movimentacao
         JOIN material_produto mp ON tp.id_produto = mp.id_produto
GROUP BY tp.id_produto, mp.descricao, t.id_almoxarifado;

-- -----------------------------------------------------
-- Table `wegia`.`imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`imagem` (
  `id_imagem` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `imagem` LONGTEXT NULL DEFAULT NULL,
  `tipo` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_imagem`),
  UNIQUE INDEX `nome` (`nome` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`situacao_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`situacao_funcionario` (
  `id_situacao_funcionario` INT(11) NOT NULL AUTO_INCREMENT,
  `data_hora` DATETIME NULL DEFAULT NULL,
  `descricao` VARCHAR(50) NULL DEFAULT NULL,
  `imagem` LONGTEXT NULL DEFAULT NULL,
  `imagem_extensao` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`id_situacao_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`movimentacao_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`movimentacao_funcionario` (
  `id_funcionario` INT(11) NOT NULL,
  `id_situacao_funcionario` INT(11) NOT NULL,
  PRIMARY KEY (`id_funcionario`, `id_situacao_funcionario`),
  INDEX `id_situacao_funcionario` (`id_situacao_funcionario` ASC),
  CONSTRAINT `movimentacao_funcionario_ibfk_1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `wegia`.`funcionario` (`id_funcionario`),
  CONSTRAINT `movimentacao_funcionario_ibfk_2`
    FOREIGN KEY (`id_situacao_funcionario`)
    REFERENCES `wegia`.`situacao_funcionario` (`id_situacao_funcionario`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`recurso` (
  `id_recurso` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_recurso`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`modulos_visiveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`modulos_visiveis`(
 `id_modulo` INT NOT NULL AUTO_INCREMENT,
`id_recurso` INT NOT NULL,
  `visivel` BIT NOT NULL,
  PRIMARY KEY (`id_modulo`),
  INDEX `fk_modulos_visiveis_recurso_idx` (`id_recurso` ASC),
  CONSTRAINT `fk_modulos_visiveis_recurso`
    FOREIGN KEY (`id_recurso`)
    REFERENCES `wegia`.`recurso` (`id_recurso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`escala_quadro_horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`escala_quadro_horario` (
  `id_escala` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_escala`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wegia`.`tipo_quadro_horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`tipo_quadro_horario` (
  `id_tipo` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `wegia`.`quadro_horario_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`quadro_horario_funcionario` (
  `id_quadro_horario` INT(11) NOT NULL AUTO_INCREMENT,
  `id_funcionario` INT(11) NOT NULL,
  `escala` INT(11) NOT NULL,
  `tipo` INT(11) NOT NULL,
  `carga_horaria` VARCHAR(200) NULL DEFAULT NULL,
  `entrada1` VARCHAR(200) NULL DEFAULT NULL,
  `saida1` VARCHAR(200) NULL DEFAULT NULL,
  `entrada2` VARCHAR(200) NULL DEFAULT NULL,
  `saida2` VARCHAR(200) NULL DEFAULT NULL,
  `total` VARCHAR(200) NULL DEFAULT NULL,
  `dias_trabalhados` VARCHAR(200) NULL DEFAULT NULL,
  `folga` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_quadro_horario`),
  INDEX `id_funcionario` (`id_funcionario` ASC),
  INDEX `quadro_horario_funcionario_ibfk_2` (`escala` ASC),
  INDEX `quadro_horario_funcionario_ibfk_3` (`tipo` ASC),
  CONSTRAINT `quadro_horario_funcionario_ibfk_1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `wegia`.`funcionario` (`id_funcionario`),
  CONSTRAINT `quadro_horario_funcionario_ibfk_2`
    FOREIGN KEY (`escala`)
    REFERENCES `wegia`.`escala_quadro_horario` (`id_escala`),
  CONSTRAINT `quadro_horario_funcionario_ibfk_3`
    FOREIGN KEY (`tipo`)
    REFERENCES `wegia`.`tipo_quadro_horario` (`id_tipo`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`selecao_paragrafo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`selecao_paragrafo` (
  `id_selecao` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_campo` VARCHAR(40) NOT NULL,
  `paragrafo` TEXT NOT NULL,
  `original` TINYINT(4) NULL DEFAULT '1',
  PRIMARY KEY (`id_selecao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`contato_instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`contato_instituicao` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `descricao` VARCHAR(256) NOT NULL,
    `contato` VARCHAR(256) NOT NULL,
    PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`tabela_imagem_campo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`tabela_imagem_campo` (
  `id_relacao` INT(11) NOT NULL AUTO_INCREMENT,
  `id_campo` INT(11) NOT NULL,
  `id_imagem` INT(11) NOT NULL,
  PRIMARY KEY (`id_relacao`),
  INDEX `id_campo` (`id_campo` ASC),
  INDEX `id_imagem` (`id_imagem` ASC),
  CONSTRAINT `tabela_imagem_campo_ibfk_1`
    FOREIGN KEY (`id_campo`)
    REFERENCES `wegia`.`campo_imagem` (`id_campo`),
  CONSTRAINT `tabela_imagem_campo_ibfk_2`
    FOREIGN KEY (`id_imagem`)
    REFERENCES `wegia`.`imagem` (`id_imagem`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`contribuicao_gatewayPagamento`
-- -----------------------------------------------------
CREATE TABLE `wegia`.`contribuicao_gatewayPagamento` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `plataforma` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`contribuicao_regras`
-- -----------------------------------------------------
CREATE TABLE `wegia`.`contribuicao_regras` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `regra` VARCHAR(128) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `regra_UNIQUE` (`regra` ASC) VISIBLE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`contribuicao_meioPagamento`
-- -----------------------------------------------------
CREATE TABLE `wegia`.`contribuicao_meioPagamento` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `meio` VARCHAR(45) NOT NULL,
    `id_plataforma` INT NOT NULL,
    `status` BOOLEAN NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `meio_UNIQUE` (`meio` ASC) VISIBLE,
    CONSTRAINT `fk_contribuicao_gatewayPagamento_plataforma`
        FOREIGN KEY (`id_plataforma`)
        REFERENCES `wegia`.`contribuicao_gatewayPagamento` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`contribuicao_conjuntoRegras`
-- -----------------------------------------------------
CREATE TABLE `wegia`.`contribuicao_conjuntoRegras` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `id_meioPagamento` INT,
    `id_regra` INT,
    `valor` DECIMAL(10, 2),
    `status` BOOLEAN NOT NULL,
    CONSTRAINT `fk_contribuicao_meioPagamento` FOREIGN KEY (`id_meioPagamento`) REFERENCES `wegia`.`contribuicao_meioPagamento`(`id`),
    CONSTRAINT `fk_contribuicao_regras` FOREIGN KEY (`id_regra`) REFERENCES `wegia`.`contribuicao_regras`(`id`),
    CONSTRAINT `unico_meioPagamento_regra` UNIQUE (`id_meioPagamento`, `id_regra`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`recorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS wegia.recorrencia (
    id INT NOT NULL AUTO_INCREMENT,
    id_socio INT(11) NOT NULL,
    id_gateway INT(11) NOT NULL,
    codigo VARCHAR(255) NOT NULL UNIQUE,
    valor DECIMAL(10,2) NOT NULL,
    data_inicio DATE NOT NULL,
    data_termino DATE,
    status BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (id),
    CONSTRAINT FK_recorrencia_socios
    FOREIGN KEY (id_socio)
    REFERENCES wegia.socio (id_socio),
    CONSTRAINT FK_recorrencia_gateways
    FOREIGN KEY (id_gateway)
    REFERENCES wegia.contribuicao_gatewayPagamento (id)
)ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`contribuicao_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS wegia.contribuicao_log (
    id INT NOT NULL AUTO_INCREMENT,
    id_socio INT(11) NOT NULL,
    id_gateway INT(11) NOT NULL,
    id_meio_pagamento INT(11) NOT NULL,
    id_recorrencia INT(11) DEFAULT NULL,
    codigo VARCHAR(255) NOT NULL UNIQUE,
    valor DECIMAL(10,2) NOT NULL,
    data_geracao DATE NOT NULL,
    data_vencimento DATE NOT NULL,
    data_pagamento DATE,
    status_pagamento BOOLEAN NOT NULL,
    url LONGTEXT DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_id_socios
    FOREIGN KEY (id_socio)
    REFERENCES wegia.socio (id_socio),
    CONSTRAINT FK_id_gateways
    FOREIGN KEY (id_gateway)
    REFERENCES wegia.contribuicao_gatewayPagamento (id),
    CONSTRAINT FK_id_meio_pagamentos
    FOREIGN KEY (id_meio_pagamento)
    REFERENCES wegia.contribuicao_meioPagamento (id),
    CONSTRAINT FK_id_recorrencia
    FOREIGN KEY (id_recorrencia)
    REFERENCES wegia.recorrencia (id)
)ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`socio_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`socio_status` (
  `id_sociostatus` INT NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_sociostatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`socio_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`socio_tipo` (
  `id_sociotipo` INT NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_sociotipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`socio_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`socio_tag` (
  `id_sociotag` INT NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(255) NOT NULL,
  UNIQUE INDEX (`tag` ASC),
  PRIMARY KEY (`id_sociotag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`socio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`socio` (
  `id_socio` INT(11) NOT NULL AUTO_INCREMENT,
  `id_pessoa` INT(11) NOT NULL,
  `id_sociostatus` INT NOT NULL,
  `id_sociotipo` INT NOT NULL,
  `id_sociotag` INT NULL DEFAULT NULL,
  `email` VARCHAR(256) NULL DEFAULT NULL,
  `valor_periodo` DECIMAL(10,2) NULL DEFAULT NULL,
  `data_referencia` DATE NULL DEFAULT NULL,
  UNIQUE INDEX (`id_pessoa` ASC),
  PRIMARY KEY (`id_socio`),
  INDEX `fk_socio_socio_status1_idx` (`id_sociostatus` ASC),
  INDEX `fk_socio_pessoa1_idx` (`id_pessoa` ASC),
  INDEX `fk_socio_socio_tipo1_idx` (`id_sociotipo` ASC),
  INDEX `fk_socio_socio_tag1_idx` (`id_sociotag` ASC),
  CONSTRAINT `fk_socio_socio_status1`
    FOREIGN KEY (`id_sociostatus`)
    REFERENCES `wegia`.`socio_status` (`id_sociostatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_socio_pessoa1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `wegia`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_socio_socio_tipo1`
    FOREIGN KEY (`id_sociotipo`)
    REFERENCES `wegia`.`socio_tipo` (`id_sociotipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_socio_socio_tag1`
    FOREIGN KEY (`id_sociotag`)
    REFERENCES `wegia`.`socio_tag` (`id_sociotag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`socio_log`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `wegia`.`socio_log` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `id_socio` INT,
  `data` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `descricao` VARCHAR(255) NOT NULL,
  FOREIGN KEY (`id_socio`) REFERENCES `socio`(`id_socio`)
)ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`endereco_instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`endereco_instituicao` (
  `id_inst` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(256) NOT NULL,
  `numero_endereco` VARCHAR(256) NOT NULL,
  `logradouro` VARCHAR(256) NOT NULL,
  `bairro` VARCHAR(256) NULL DEFAULT NULL,
  `cidade` VARCHAR(256) NOT NULL,
  `estado` VARCHAR(256) NOT NULL,
  `cep` VARCHAR(256) NOT NULL,
  `complemento` VARCHAR(256) NULL DEFAULT NULL,
  `ibge` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id_inst`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`atendido_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`atendido_tipo` (
  `idatendido_tipo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idatendido_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`atendido_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`atendido_status` (
  `idatendido_status` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(255) NULL,
  PRIMARY KEY (`idatendido_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`atendido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`atendido` (
  `idatendido` INT NOT NULL AUTO_INCREMENT,
  `pessoa_id_pessoa` INT(11) NOT NULL,
  `atendido_tipo_idatendido_tipo` INT NOT NULL,
  `atendido_status_idatendido_status` INT NOT NULL,
  PRIMARY KEY (`idatendido`),
  INDEX `fk_atendido_pessoa1_idx` (`pessoa_id_pessoa` ASC),
  INDEX `fk_atendido_atendido_tipo1_idx` (`atendido_tipo_idatendido_tipo` ASC),
  INDEX `fk_atendido_atentido_status1_idx` (`atendido_status_idatendido_status` ASC),
  CONSTRAINT `fk_atendido_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `wegia`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atendido_atendido_tipo1`
    FOREIGN KEY (`atendido_tipo_idatendido_tipo`)
    REFERENCES `wegia`.`atendido_tipo` (`idatendido_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atendido_atentido_status1`
    FOREIGN KEY (`atendido_status_idatendido_status`)
    REFERENCES `wegia`.`atendido_status` (`idatendido_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`atendido_contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`atendido_contato` (
  `idatendido_contato` INT NOT NULL AUTO_INCREMENT,
  `atendido_idatendido` INT NOT NULL,
  `pessoa_id_pessoa` INT(11) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idatendido_contato`),
  INDEX `fk_atentido_contato_atendido1_idx` (`atendido_idatendido` ASC),
  INDEX `fk_atentido_contato_pessoa1_idx` (`pessoa_id_pessoa` ASC),
  CONSTRAINT `fk_atentido_contato_atendido1`
    FOREIGN KEY (`atendido_idatendido`)
    REFERENCES `wegia`.`atendido` (`idatendido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atentido_contato_pessoa1`
    FOREIGN KEY (`pessoa_id_pessoa`)
    REFERENCES `wegia`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`atendido_ocorrencia_tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`atendido_ocorrencia_tipos` (
  `idatendido_ocorrencia_tipos` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`idatendido_ocorrencia_tipos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`atendido_ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`atendido_ocorrencia` (
  `idatendido_ocorrencias` INT NOT NULL AUTO_INCREMENT,
  `atendido_idatendido` INT NOT NULL,
  `atendido_ocorrencia_tipos_idatendido_ocorrencia_tipos` INT NOT NULL,
  `funcionario_id_funcionario` INT(11) NOT NULL,
  `data` DATE NOT NULL,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`idatendido_ocorrencias`),
  INDEX `fk_atentido_ocorrencias_atendido1_idx` (`atendido_idatendido` ASC),
  INDEX `fk_atentido_ocorrencias_atendido_ocorrencia_tipos1_idx` (`atendido_ocorrencia_tipos_idatendido_ocorrencia_tipos` ASC),
  INDEX `fk_atentido_ocorrencias_funcionario1_idx` (`funcionario_id_funcionario` ASC),
  CONSTRAINT `fk_atentido_ocorrencias_atendido1`
    FOREIGN KEY (`atendido_idatendido`)
    REFERENCES `wegia`.`atendido` (`idatendido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atentido_ocorrencias_atendido_ocorrencia_tipos1`
    FOREIGN KEY (`atendido_ocorrencia_tipos_idatendido_ocorrencia_tipos`)
    REFERENCES `wegia`.`atendido_ocorrencia_tipos` (`idatendido_ocorrencia_tipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atentido_ocorrencias_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `wegia`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`atendido_ocorrencia_doc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`atendido_ocorrencia_doc` (
  `idatendido_ocorrencia_doc` INT NOT NULL AUTO_INCREMENT,
  `atentido_ocorrencia_idatentido_ocorrencias` INT NOT NULL,
  `data` TIMESTAMP NOT NULL,
  `arquivo_nome` VARCHAR(255) NOT NULL,
  `arquivo_extensao` VARCHAR(200) NOT NULL,
  `arquivo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idatendido_ocorrencia_doc`),
  INDEX `fk_atendido_ocorrencia_doc_atentido_ocorrencia1_idx` (`atentido_ocorrencia_idatentido_ocorrencias` ASC),
  CONSTRAINT `fk_atendido_ocorrencia_doc_atentido_ocorrencia1`
    FOREIGN KEY (`atentido_ocorrencia_idatentido_ocorrencias`)
    REFERENCES `wegia`.`atendido_ocorrencia` (`idatendido_ocorrencias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------------------------
-- Table `wegia`.`pa_status`
-- -----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pa_status`(
    `id` INT NOT NULL AUTO_INCREMENT,
    `descricao` VARCHAR(512) NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;

-- -----------------------------------------------------------------------
-- Table `wegia`.`processo_de_aceitacao`
-- -----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`processo_de_aceitacao`(
    `id` INT NOT NULL AUTO_INCREMENT,
    `data_inicio` DATETIME NOT NULL,
    `data_fim` DATETIME NULL,
    `descricao` VARCHAR(512) NOT NULL,
    `id_status` INT NOT NULL,
    `id_pessoa` INT NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_processo_status`
    FOREIGN KEY (`id_status`)
    REFERENCES `wegia`.`pa_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_processo_pessoa`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `wegia`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

-- -----------------------------------------------------------------------
-- Table `wegia`.`pa_etapa`
-- -----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pa_etapa`(
    `id` INT NOT NULL AUTO_INCREMENT,
    `data_inicio` DATETIME NOT NULL,
    `data_fim` DATETIME NULL,
    `descricao` VARCHAR(512) NOT NULL,
    `id_processo` INT NOT NULL,
    `id_status` INT NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_etapa_processo`
    FOREIGN KEY (`id_processo`)
    REFERENCES `wegia`.`processo_de_aceitacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_etapa_status`
    FOREIGN KEY (`id_status`)
    REFERENCES `wegia`.`pa_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

-- -----------------------------------------------------------------------
-- Table `wegia`.`pa_arquivo`
-- -----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pa_arquivo`(
    `id` INT NOT NULL AUTO_INCREMENT,
    `id_processo` INT NULL,
    `id_etapa` INT NULL,
    `arquivo_nome` VARCHAR(255) NOT NULL,
    `arquivo_extensao` VARCHAR(10) NOT NULL,
    `arquivo` VARCHAR(255) NOT NULL,
    `data_upload` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_pa_arquivo_processo`
    FOREIGN KEY (`id_processo`)
    REFERENCES `wegia`.`processo_de_aceitacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_pa_arquivo_etapa`
    FOREIGN KEY (`id_etapa`)
    REFERENCES `wegia`.`pa_etapa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;

-- -----------------------------------------------------------------------
-- Table `wegia`.`etapa_arquivo`
-- -----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`etapa_arquivo`(
    `id` INT NOT NULL AUTO_INCREMENT,
    `etapa_id` INT NOT NULL,
    `arquivo_nome` VARCHAR(255) NOT NULL,
    `arquivo_extensao` VARCHAR(10) NOT NULL,
    `arquivo` VARCHAR(255) NOT NULL,
    `data_upload` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_etapa_arquivo_etapa`
    FOREIGN KEY (`etapa_id`)
    REFERENCES `wegia`.`pa_etapa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`funcionario_remuneracao_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`funcionario_remuneracao_tipo` (
  `idfuncionario_remuneracao_tipo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idfuncionario_remuneracao_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`funcionario_remuneracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`funcionario_remuneracao` (
  `idfuncionario_remuneracao` INT NOT NULL AUTO_INCREMENT,
  `funcionario_id_funcionario` INT(11) NOT NULL,
  `funcionario_remuneracao_tipo_idfuncionario_remuneracao_tipo` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `inicio` DATE NULL,
  `fim` DATE NULL,
  PRIMARY KEY (`idfuncionario_remuneracao`),
  INDEX `fk_funcionario_remuneracao_funcionario1_idx` (`funcionario_id_funcionario` ASC),
  INDEX `fk_funcionario_remuneracao_funcionario_remuneracao_tipo1_idx` (`funcionario_remuneracao_tipo_idfuncionario_remuneracao_tipo` ASC),
  CONSTRAINT `fk_funcionario_remuneracao_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `wegia`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_remuneracao_funcionario_remuneracao_tipo1`
    FOREIGN KEY (`funcionario_remuneracao_tipo_idfuncionario_remuneracao_tipo`)
    REFERENCES `wegia`.`funcionario_remuneracao_tipo` (`idfuncionario_remuneracao_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`funcionario_listainfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`funcionario_listainfo` (
  `idfuncionario_listainfo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`idfuncionario_listainfo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`funcionario_outrasinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`funcionario_outrasinfo` (
  `idfunncionario_outrasinfo` INT NOT NULL AUTO_INCREMENT,
  `funcionario_id_funcionario` INT(11) NOT NULL,
  `funcionario_listainfo_idfuncionario_listainfo` INT NOT NULL,
  `dado` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idfunncionario_outrasinfo`),
  INDEX `fk_funncionario_outrasinfo_funcionario1_idx` (`funcionario_id_funcionario` ASC),
  INDEX `fk_funcionario_outrasinfo_funcionario_listainfo1_idx` (`funcionario_listainfo_idfuncionario_listainfo` ASC),
  CONSTRAINT `fk_funncionario_outrasinfo_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `wegia`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_outrasinfo_funcionario_listainfo1`
    FOREIGN KEY (`funcionario_listainfo_idfuncionario_listainfo`)
    REFERENCES `wegia`.`funcionario_listainfo` (`idfuncionario_listainfo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`saude_fichamedica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`saude_fichamedica` (
    `id_fichamedica` INT NOT NULL AUTO_INCREMENT,
    `id_pessoa` INT NOT NULL,
    `prontuario` TEXT NOT NULL,
    PRIMARY KEY (`id_fichamedica`),
    INDEX `fk_saude_fichamedica_pessoa_idx` (`id_pessoa` ASC),
    CONSTRAINT `fk_saude_fichamedica_pessoa`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `wegia`.`pessoa` (`id_pessoa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`saude_fichamedica_prontuario_historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`saude_fichamedica_prontuario_historico` (
    `id_prontuario_historico` INT NOT NULL AUTO_INCREMENT,
    `id_fichamedica` INT NOT NULL,
    `prontuario` TEXT NOT NULL,
    `data` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id_prontuario_historico`),
    INDEX `fk_saude_fichamedica_prontuario_historico_fichamedica_idx` (`id_fichamedica` ASC),
    CONSTRAINT `fk_saude_fichamedica_prontuario_historico_fichamedica`
    FOREIGN KEY (`id_fichamedica`)
    REFERENCES `wegia`.`saude_fichamedica` (`id_fichamedica`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`saude_alergia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS saude_alergia (
    id_alergia INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(150) NOT NULL
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`saude_fichamedica_alergia`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS saude_fichamedica_alergia (
    id_fichamedica_alergia INT AUTO_INCREMENT PRIMARY KEY,
    id_fichamedica INT NOT NULL,
    id_alergia INT NOT NULL,
    UNIQUE KEY uk_fichamedica_alergia (id_fichamedica, id_alergia),
    CONSTRAINT fk_fichamedica_alergia FOREIGN KEY (id_fichamedica) REFERENCES saude_fichamedica(id_fichamedica) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_alergia FOREIGN KEY (id_alergia) REFERENCES saude_alergia(id_alergia) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`saude_tabelacid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`saude_tabelacid` (
  `id_CID` INT NOT NULL AUTO_INCREMENT,
  `CID` VARCHAR(10) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_CID`),
  UNIQUE INDEX `CID_UNIQUE` (`CID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`saude_enfermidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`saude_enfermidades` (
  `id_enfermidade` INT NOT NULL AUTO_INCREMENT,
  `id_fichamedica` INT NOT NULL,
  `id_CID` INT NOT NULL,
  `data_diagnostico` DATE NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`id_enfermidade`),
  INDEX `fk_daude_enfermidades_saude_fichamedica1_idx` (`id_fichamedica` ASC),
  INDEX `fk_saude_enfermidades_saude_CID1_idx` (`id_CID` ASC),
  CONSTRAINT `fk_daude_enfermidades_saude_fichamedica1`
    FOREIGN KEY (`id_fichamedica`)
    REFERENCES `wegia`.`saude_fichamedica` (`id_fichamedica`)
    ON DELETE NO ACTION

    ON UPDATE NO ACTION,
  CONSTRAINT `fk_saude_enfermidades_saude_CID1`
    FOREIGN KEY (`id_CID`)
    REFERENCES `wegia`.`saude_tabelacid` (`id_CID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`saude_exame_tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`saude_exame_tipos` (
  `id_exame_tipo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_exame_tipo`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`saude_exames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`saude_exames` (
                                                      `id_exame` INT NOT NULL AUTO_INCREMENT,
                                                      `id_fichamedica` INT NOT NULL,
                                                      `id_exame_tipo` INT NOT NULL,
                                                      `data` TIMESTAMP NOT NULL,
                                                      `arquivo_nome` VARCHAR(255) NOT NULL,
    `arquivo_extensao` VARCHAR(10) NULL,
    `arquivo` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id_exame`),
    INDEX `fk_saude_exames_saude_fichamedica1_idx` (`id_fichamedica` ASC),
    INDEX `fk_saude_exames_saude_exame_tipos1_idx` (`id_exame_tipo` ASC),
    CONSTRAINT `fk_saude_exames_saude_fichamedica1`
    FOREIGN KEY (`id_fichamedica`)
    REFERENCES `wegia`.`saude_fichamedica` (`id_fichamedica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_saude_exames_saude_exame_tipos1`
    FOREIGN KEY (`id_exame_tipo`)
    REFERENCES `wegia`.`saude_exame_tipos` (`id_exame_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`saude_medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`saude_medicos` (
    `id_medico` INT NOT NULL AUTO_INCREMENT,
    `crm` CHAR(10) NULL,
    `nome` VARCHAR(50) NULL,
    PRIMARY KEY (`id_medico`),
    CONSTRAINT `uq_nome_crm` UNIQUE (`crm`, `nome`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`saude_atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`saude_atendimento` (
    `id_atendimento` INT NOT NULL AUTO_INCREMENT,
    `id_fichamedica` INT NOT NULL,
    `id_funcionario` INT(11) NOT NULL,
    `id_medico` INT NOT NULL,
    `data_registro` DATE NULL  DEFAULT CURRENT_TIMESTAMP,
    `data_atendimento` DATE NULL,
    `descricao` TEXT NULL,
    PRIMARY KEY (`id_atendimento`),
    INDEX `fk_saude_atendimento_saude_fichamedica1_idx` (`id_fichamedica` ASC),
    INDEX `fk_saude_atendimento_funcionario1_idx` (`id_funcionario` ASC),
    INDEX `fk_saude_atendimento_medico1_idx` (`id_medico` ASC),
    CONSTRAINT `fk_saude_atendimento_saude_fichamedica1`
    FOREIGN KEY (`id_fichamedica`)
    REFERENCES `wegia`.`saude_fichamedica` (`id_fichamedica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_saude_atendimento_medico1`
    FOREIGN KEY (`id_medico`)
    REFERENCES `wegia`.`saude_medicos` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_saude_atendimento_funcionario1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `wegia`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`saude_medicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`saude_medicacao` (
  `id_medicacao` INT NOT NULL AUTO_INCREMENT,
  `id_atendimento` INT NOT NULL,
  `medicamento` VARCHAR(255) NOT NULL,
  `dosagem` VARCHAR(100) NULL,
  `horario` VARCHAR(100) NULL,
  `duracao` VARCHAR(100) NULL,
  `status` ENUM('Tratamento', 'Concluido', 'Substituido', 'Cancelado') NOT NULL DEFAULT 'Tratamento',
  PRIMARY KEY (`id_medicacao`),
  INDEX `fk_saude_medicacao_saude_atendimento1_idx` (`id_atendimento` ASC),
  CONSTRAINT `fk_saude_medicacao_saude_atendimento1`
    FOREIGN KEY (`id_atendimento`)
    REFERENCES `wegia`.`saude_atendimento` (`id_atendimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`saude_medicamento_administracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`saude_medicamento_administracao` (
  `idsaude_medicamento_administracao` INT NOT NULL AUTO_INCREMENT,
  `registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `aplicacao` DATETIME NOT NULL,
  `saude_medicacao_id_medicacao` INT NOT NULL,
  `funcionario_id_funcionario` INT(11) NOT NULL,
  PRIMARY KEY (`idsaude_medicamento_administracao`),
  INDEX `fk_saude_medicamento_administracao_saude_medicacao1_idx` (`saude_medicacao_id_medicacao` ASC),
  INDEX `fk_saude_medicamento_administracao_funcionario1_idx` (`funcionario_id_funcionario` ASC),
  CONSTRAINT `fk_saude_medicamento_administracao_saude_medicacao1`
    FOREIGN KEY (`saude_medicacao_id_medicacao`)
    REFERENCES `wegia`.`saude_medicacao` (`id_medicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_saude_medicamento_administracao_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `wegia`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wegia`.`saude_sinais_vitais
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`saude_sinais_vitais` (
  `id_sinais_vitais` INT NOT NULL AUTO_INCREMENT,
  `id_fichamedica` INT NOT NULL,
  `id_funcionario` INT(11) NOT NULL,
  `data` TIMESTAMP NOT NULL,
  `saturacao` DECIMAL(5,2) NULL DEFAULT NULL,
  `pressao_arterial` VARCHAR(10) NULL DEFAULT NULL,
  `frequencia_cardiaca` INT(5) NULL DEFAULT NULL,
  `frequencia_respiratoria` INT(5) NULL DEFAULT NULL,
  `temperatura` DECIMAL(7,2) NULL DEFAULT NULL,
  `hgt` DECIMAL(7,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_sinais_vitais`),
  INDEX `fk_saude_sinais_vitais_saude_fichamedica1_idx` (`id_fichamedica` ASC),
  INDEX `fk_saude_sinais_vitais_funcionario1_idx` (`id_funcionario` ASC),
  CONSTRAINT `fk_saude_sinais_vitais_saude_fichamedica1`
    FOREIGN KEY (`id_fichamedica`)
    REFERENCES `wegia`.`saude_fichamedica` (`id_fichamedica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_saude_sinais_vitais_funcionario1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `wegia`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`saude_intercorrencia
-- -----------------------------------------------------
CREATE TABLE saude_intercorrencia (
    id_intercorrencia INT AUTO_INCREMENT PRIMARY KEY,
    data DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    descricao TEXT NOT NULL,
    id_funcionario INT NOT NULL,
    id_fichamedica INT NOT NULL,
    CONSTRAINT fk_intercorrencia_funcionario
        FOREIGN KEY (id_funcionario) REFERENCES funcionario(id_funcionario)
            ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_intercorrencia_fichamedica
        FOREIGN KEY (id_fichamedica) REFERENCES saude_fichamedica(id_fichamedica)
        ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = InnoDB;

-- -------------------------------------------------------
-- Table `wegia`.`pet_foto`
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pet_foto` (
    `id_pet_foto` INT NOT NULL AUTO_INCREMENT,
    `arquivo_foto_pet` VARCHAR(255) NOT NULL,
    `arquivo_foto_pet_nome` varchar(200) NOT NULL,
    `arquivo_foto_pet_extensao` varchar(50) NOT NULL,
    PRIMARY KEY (`id_pet_foto`)
)ENGINE = InnoDB;

-- -------------------------------------------------------
-- Table `wegia`.`pet_especie`
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pet_especie` (
    `id_pet_especie` INT NOT NULL AUTO_INCREMENT,
    `descricao` VARCHAR(200) NOT NULL,
    PRIMARY KEY (`id_pet_especie`))
ENGINE = InnoDB;

-- --------------------------------------------------------
-- Table `wegia`.`pet_raca`
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pet_raca` (
    `id_pet_raca` INT NOT NULL AUTO_INCREMENT,
    `descricao` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`id_pet_raca`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wegia`.`pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pet` (
    `id_pet` INT(11) NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(200) NOT NULL,
    `data_nascimento` DATE NOT NULL,
    `data_acolhimento` DATE NOT NULL,
    `sexo` CHAR(1) NOT NULL,
    `caracteristicas_especificas` VARCHAR(250) NULL,
    `id_pet_foto` INT NULL,
    `id_pet_especie` INT NOT NULL,
    `id_pet_raca` INT NOT NULL,
    `cor` ENUM(
        'Preto',
        'Branco',
        'Cinza',
        'Marrom',
        'Caramelo',
        'Amarelo',
        'Bege',
        'Dourado',
        'Ruivo',
        'Creme',
        'Azul',
        'Chocolate',
        'Bicolor',
        'Tricolor'
    )  NOT NULL,
    PRIMARY KEY (`id_pet`),
    CONSTRAINT `fk_pet_especie`
    FOREIGN KEY (`id_pet_especie`)
    REFERENCES `wegia`.`pet_especie` (`id_pet_especie`),
    CONSTRAINT `fk_pet_raca`
    FOREIGN KEY (`id_pet_raca`)
    REFERENCES `wegia`.`pet_raca` (`id_pet_raca`),
    CONSTRAINT `fk_pet_foto`
    FOREIGN KEY (`id_pet_foto`)
    REFERENCES `wegia`.`pet_foto`(`id_pet_foto`)
    )
    ENGINE = InnoDB;

-- ----------------------------------------------------------
-- Table `wegia`.`pet_adocao`
-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pet_adocao` (
    `id_adocao` INT NOT NULL AUTO_INCREMENT,
    `id_pessoa` INT(11) NOT NULL,
    `id_pet` INT(11) NOT NULL,
    `data_adocao` DATE NOT NULL,
    PRIMARY KEY (`id_adocao`),
    CONSTRAINT `fk_pessoa`
     FOREIGN KEY (`id_pessoa`)
     REFERENCES `wegia`.`pessoa` (`id_pessoa`)
     ON DELETE NO ACTION
     ON UPDATE NO ACTION,
    CONSTRAINT `fk_pet`
     FOREIGN KEY (`id_pet`)
     REFERENCES `wegia`.`pet` (`id_pet`)
     ON DELETE NO ACTION
     ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- -------------------------------------------------------------
-- Table `wegia`.`pet_ficha_medica`
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pet_ficha_medica` (
    `id_ficha_medica` INT NOT NULL AUTO_INCREMENT,
    `id_pet` INT(11) NOT NULL,
    `castrado` CHAR(1) NOT NULL,
    `necessidades_especiais` VARCHAR(255) NULL,
    PRIMARY KEY (`id_ficha_medica`),
    CONSTRAINT `fk_id_pet`
     FOREIGN KEY (`id_pet`)
     REFERENCES `wegia`.`pet`(`id_pet`)
     ON DELETE NO ACTION
     ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- ----------------------------------------------------------------
-- Table `wegia`.`pet_tipo_exame`
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pet_tipo_exame`(
    `id_tipo_exame` INT NOT NULL AUTO_INCREMENT,
    `descricao_exame` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id_tipo_exame`)
)ENGINE = InnoDB;

-- ---------------------------------------------------------------
-- Table  `wegia`.`pet_exame`
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pet_exame` (
    `id_exame` INT NOT NULL AUTO_INCREMENT,
    `id_ficha_medica` INT NOT NULL,
    `id_tipo_exame` INT NOT NULL,
    `data_exame` DATE NOT NULL,
    `arquivo_exame` LONGBLOB NOT NULL,
    `arquivo_nome` VARCHAR(200) NOT NULL,
    `arquivo_extensao` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`id_exame`),
    CONSTRAINT `fk_pet_ficha_medica`
     FOREIGN KEY (`id_ficha_medica`)
     REFERENCES `wegia`.`pet_ficha_medica` (`id_ficha_medica`)
     ON DELETE NO ACTION
     ON UPDATE NO ACTION,
    CONSTRAINT `fk_pet_tipo_exame`
     FOREIGN KEY (`id_tipo_exame`)
     REFERENCES `wegia`.`pet_tipo_exame` (`id_tipo_exame`)
     ON DELETE NO ACTION
     ON UPDATE NO ACTION
)ENGINE = InnoDB;


-- ------------------------------------------------------------------
-- Table `wegia`.`pet_vacina`
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pet_vacina`(
    `id_vacina` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(200) NOT NULL,
    `marca` VARCHAR(45) NULL,
    PRIMARY KEY (`id_vacina`)
)ENGINE = InnoDB;

-- -----------------------------------------------------------------
-- Table `wegia`.`pet_vacinacao`
-- -----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pet_vacinacao`(
    `id_vacinacao` INT NOT NULL AUTO_INCREMENT,
    `id_vacina` INT NOT NULL,
    `id_ficha_medica` INT NOT NULL,
    `data_vacinacao` DATE NOT NULL,
    PRIMARY KEY (`id_vacinacao`),
    CONSTRAINT `fk_vacina_pet`
     FOREIGN KEY (`id_vacina`)
     REFERENCES `wegia`.`pet_vacina` (`id_vacina`)
     ON DELETE NO ACTION
     ON UPDATE NO ACTION,
    CONSTRAINT `fk_ficha_medica_pet`
     FOREIGN KEY (`id_ficha_medica`)
     REFERENCES `wegia`.`pet_ficha_medica` (`id_ficha_medica`)
     ON DELETE NO ACTION
     ON UPDATE NO ACTION
)ENGINE = InnoDB;


-- ------------------------------------------------------------------
-- Table `wegia`.`pet_vermifugo`
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pet_vermifugo`(
    `id_vermifugo` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(200) NOT NULL,
    `marca` VARCHAR(45) NULL,
    PRIMARY KEY (`id_vermifugo`)
)ENGINE = InnoDB;

-- -----------------------------------------------------------------
-- Table `wegia`.`pet_vermifugacao`
-- -----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pet_vermifugacao`(
    `id_vermifugacao` INT NOT NULL AUTO_INCREMENT,
    `id_vermifugo` INT NOT NULL,
    `id_ficha_medica_vermifugo` INT NOT NULL,
    `data_vermifugacao` DATE NOT NULL,
    PRIMARY KEY (`id_vermifugacao`),
    CONSTRAINT `fk_vermifugo_pet`
     FOREIGN KEY (`id_vermifugo`)
     REFERENCES `wegia`.`pet_vermifugo` (`id_vermifugo`)
     ON DELETE NO ACTION
     ON UPDATE NO ACTION,
    CONSTRAINT `fk_ficha_medica_vermifugo`
     FOREIGN KEY (`id_ficha_medica_vermifugo`)
     REFERENCES `wegia`.`pet_ficha_medica` (`id_ficha_medica`)
     ON DELETE NO ACTION
     ON UPDATE NO ACTION
)ENGINE = InnoDB;


-- -------------------------------------------------------------------
-- Table `wegia`.`pet_atendimento`
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pet_atendimento`(
    `id_pet_atendimento` INT NOT NULL AUTO_INCREMENT,
    `id_ficha_medica` INT NOT NULL,
    `data_atendimento` DATE NOT NULL,
    `descricao` TEXT NOT NULL,
    PRIMARY KEY (`id_pet_atendimento`),
    CONSTRAINT `fk_ficha_pet_medica`
     FOREIGN KEY (`id_ficha_medica`)
     REFERENCES `wegia`.`pet_ficha_medica` (`id_ficha_medica`)
     ON DELETE NO ACTION
     ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- ----------------------------------------------------------------------
-- Table `wegia`.`pet_medicamento`
-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pet_medicamento`(
    `id_medicamento` INT NOT NULL AUTO_INCREMENT,
    `nome_medicamento` VARCHAR(200) NOT NULL,
    `descricao_medicamento` VARCHAR(200) NOT NULL,
    `aplicacao` VARCHAR(250) NOT NULL,
    PRIMARY KEY (`id_medicamento`))
ENGINE = InnoDB;


-- --------------------------------------------------------------------
-- Table `wegia`.`pet_medicacao`
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pet_medicacao` (
    `id_medicacao` INT NOT NULL AUTO_INCREMENT,
    `id_medicamento` INT NOT NULL,
    `id_pet_atendimento` INT NOT NULL,
    `data_medicacao` DATE NULL,
    /*`dosagem` VARCHAR(100) NULL,
    `horario` VARCHAR(100) NULL,
    `duracao` VARCHAR(100) NULL,*/
    PRIMARY KEY (`id_medicacao`),
    CONSTRAINT `fk_pet_medicamento`
     FOREIGN KEY (`id_medicamento`)
     REFERENCES `wegia`.`pet_medicamento` (`id_medicamento`)
     ON DELETE NO ACTION
     ON UPDATE NO ACTION,
    CONSTRAINT `fk_pet_atendimento`
     FOREIGN KEY (`id_pet_atendimento`)
     REFERENCES  `wegia`.`pet_atendimento` (`id_pet_atendimento`)
     ON DELETE NO ACTION
     ON UPDATE NO ACTION
)ENGINE = InnoDB;


-- -------------------------------------------------------------------------
-- Table `wegia`.`pet_tipo_enfermidade`
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pet_tipo_enfermidade`(
    `id_tipo_enfermidade` INT NOT NULL AUTO_INCREMENT,
    `descricao` VARCHAR(255) NOT NULL,
    PRIMARY KEY(`id_tipo_enfermidade`))
ENGINE = InnoDB;

-- -----------------------------------------------------------------------
-- Table `wegia`.`pet_enfermidade`
-- -----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pet_enfermidade`(
    `id_enfermidade` INT NOT NULL AUTO_INCREMENT,
    `id_ficha_medica` INT NOT NULL,
    `id_tipo_enfermidade` INT NOT NULL,
    `data_diagnostico` DATE NOT NULL,
    `ativo` CHAR(1) NOT NULL,
    PRIMARY KEY (`id_enfermidade`),
    CONSTRAINT `fk_ficha_medica_pet_`
     FOREIGN KEY (`id_ficha_medica`)
     REFERENCES `wegia`.`pet_ficha_medica` (`id_ficha_medica`)
     ON DELETE NO ACTION
     ON UPDATE NO ACTION,
    CONSTRAINT `fk_pet_tipo_enfermidade_`
     FOREIGN KEY (`id_tipo_enfermidade`)
     REFERENCES `wegia`.`pet_tipo_enfermidade` (`id_tipo_enfermidade`)
     ON DELETE NO ACTION
     ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -------------------------------------------------------------------------
-- Table `wegia`.`pet_medida`
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `wegia`.`pet_medida`(
    `id_pet_medida` INT NOT NULL AUTO_INCREMENT,
    `id_ficha_medica` INT NOT NULL,
    `peso` FLOAT NOT NULL,
    `data_medicao` DATE NOT NULL,
    PRIMARY KEY(`id_pet_medida`),
    CONSTRAINT `fk_ficha_pet_medica_`
     FOREIGN KEY (`id_ficha_medica`)
     REFERENCES `wegia`.`pet_ficha_medica` (`id_ficha_medica`)
     ON DELETE NO ACTION
     ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- ------------------------------------------------------
-- Table `wegia`.`aviso`
-- ------------------------------------------------------

CREATE TABLE IF NOT EXISTS `wegia`.`aviso` (
    `id_aviso` INT(11) NOT NULL AUTO_INCREMENT,
    `id_pessoa` INT(11) NOT NULL,
    `titulo` VARCHAR(255) NOT NULL,
    `descricao` TEXT NOT NULL,
    `data_criacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `nivel` ENUM('info', 'alerta', 'erro') NOT NULL DEFAULT 'info',
    `url` VARCHAR(100) NULL,
    `ativo` BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (`id_aviso`),
    FOREIGN KEY (`id_pessoa`)
        REFERENCES `wegia`.`pessoa` (`id_pessoa`)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE = InnoDB;

-- ########################### TRIGGER #################### --

USE `wegia`;

DELIMITER $$
USE `wegia`$$

CREATE TRIGGER `wegia`.`tr_despacho_aviso`
    AFTER INSERT ON `wegia`.`despacho`
    FOR EACH ROW
    BEGIN
    DECLARE memorando_titulo TEXT;

    SELECT titulo INTO memorando_titulo
    FROM memorando
    WHERE id_memorando = NEW.id_memorando;

    INSERT INTO aviso (
        id_pessoa,
        titulo,
        descricao,
        url,
        nivel,
        ativo
    ) VALUES (
                 NEW.id_destinatario,
                 memorando_titulo,
                 CONCAT('Você recebeu um novo despacho do memorando: "', memorando_titulo, '"'),
                 CONCAT('/memorando/',  NEW.id_memorando),
                 'info',
                 1
             );
END$$

USE `wegia`$$

CREATE TRIGGER `wegia`.`trg_intercorrencia_aviso`
    AFTER INSERT ON saude_intercorrencia
    FOR EACH ROW
BEGIN
    INSERT INTO aviso (id_pessoa, titulo, descricao, url, nivel)
    SELECT
        p.id_pessoa,
        CONCAT('Nova intercorrência registrada para o paciente ', pes.nome, ' ', IFNULL(pes.sobrenome, '')) AS titulo,
        NEW.descricao,
        CONCAT('/saude/ficha-medica/', NEW.id_fichamedica) AS url,
        'info'
    FROM pessoa p
        JOIN funcionario f ON p.id_pessoa = f.id_pessoa
        JOIN perfil pf ON f.id_perfil = pf.id_perfil
        JOIN perfil_permissao pp ON pf.id_perfil = pp.id_perfil
        JOIN permissao prm ON pp.id_permissao = prm.id_permissao
        JOIN saude_fichamedica sfm ON sfm.id_fichamedica = NEW.id_fichamedica
        JOIN pessoa pes ON pes.id_pessoa = sfm.id_pessoa
    WHERE prm.nome = 'Visualizar Saúde Intercorrência'
        AND f.id_funcionario <> NEW.id_funcionario;
END$$

USE `wegia`$$

CREATE TRIGGER `wegia`.`tr_material_transacao_produto_insert`
        AFTER INSERT ON material_transacao_produto
        FOR EACH ROW
    BEGIN
        DECLARE v_responsavel INT;

        SELECT id_responsavel
        INTO v_responsavel
        FROM material_transacao
        WHERE id_transacao = NEW.id_transacao
            LIMIT 1;

        INSERT INTO material_transacao_produto_logs (
            id_transacao_produto,
            id_transacao,
            id_produto,
            quantidade,
            valor_unitario,
            id_usuario_acao,
            acao,
            data_acao
        ) VALUES (
                     NEW.id_transacao_produto,
                     NEW.id_transacao,
                     NEW.id_produto,
                     NEW.quantidade,
                     NEW.valor_unitario,
                     v_responsavel,
                     'create',
                     NOW()
                 );
END$$

DELIMITER ;d

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
