- name: Deploy Front
  hosts: hosts
  remote_user: azureuser
  vars:
    front_image: castilhoeduardo/wegia-front:latest
    front_container_name: wegia-front

  handlers:
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
      become: true

  tasks:
    - name: Ping My Hosts
      ping:

    - name: Update Apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      become: true

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      become: true

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
      become: true

    - name: Copy Nginx Conf
      template:
        src: ../../nginx/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      become: true
      notify: Restart Nginx

    - name: Start Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes
      become: true

    - name: Push Front Image
      command: docker pull {{front_image}}
      become: true

    - name: Remove Older Container
      command: docker rm -f {{front_container_name}}
      become: true
      ignore_errors: true

    - name: Start Front Container
      command: >
        docker run -d
        -p 3000:3000
        -e BASE_URL_API_WEGIA={{base_url_api_wegia}}
        -e BASE_URL_API_WEGIA_PATH={{base_url_api_wegia_path}}
        -e BASE_URL_API_PAGAR_ME={{base_url_api_pagar_me}}
        -e PUBLIC_KEY_PAGAR_ME={{public_key_pagar_me}}
        -e BASE_URL_API_CEP={{base_url_api_cep}}
        --name {{front_container_name}}
        {{front_image}}
      become: true
